database:
  protocol: "mongodb"
  host: "127.0.0.1"
  port: "27017"
  name: "product-service"
  user: "product"
  password: "password"
redis:
  address: "localhost:6379"
  password: "password"
server:
  httpUrl: "127.0.0.1"
  httpPort: "8080"
  httpAllowedOrigins: "http://127.0.0.1:3000,http://127.0.0.1:8080"
  grpcUrl: "127.0.0.1"
  grpcPort: "8090"
app: 
  name: "product-service"
  env: "development"
token: 
  duration: "1h"
  secret: ""
  issuer: "owner-service"
discovery:
  ownerUrl: "127.0.0.1:8091"