database:
  protocol: "mongodb"
  host: "127.0.0.1"
  port: "27017"
  name: "owner-service"
  user: "owner"
  password: "password"
redis:
  address: "localhost:6379"
  password: "password"
server:
  httpUrl: "127.0.0.1"
  httpPort: "8080"
  httpAllowedOrigins: "http://127.0.0.1:3000,http://127.0.0.1:8080"
app: 
  name: "owner-service"
  env: "development"
token: 
  duration: "1h"
  secret: ""
admin:
  email: "owner-admin@gmail.com"
  password: "password"