database:
  protocol: "mongodb"
  host: "127.0.0.1"
  port: "27018"
  name: "owner-service"
  user: "owner"
  password: "password"
redis:
  address: "localhost:6380"
  password: "password"
server:
  httpUrl: "127.0.0.1"
  httpPort: "8081"
  httpAllowedOrigins: "http://127.0.0.1:3000,http://127.0.0.1:8080"
  grpcUrl: "127.0.0.1"
  grpcPort: "8091"
app: 
  name: "owner-service"
  env: "development"
token: 
  duration: "1h"
  secret: ""
admin:
  email: "owner-admin@gmail.com"
  password: "password"
rabbitmq:
  user: "admin"
  password: "password"
  host: "localhost:5672"